name: Build and Push Bitwarden CLI Image

on:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Bitwarden CLI image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./apps/bitwarden-cli
          file: ./apps/bitwarden-cli/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bitwarden-cli:latest
            ghcr.io/${{ github.repository_owner }}/bitwarden-cli:${{ github.ref_name }}
